# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('business_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessManagerUserJoinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_manager_role', models.CharField(max_length=30)),
                ('business_manager', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='business_manager.BusinessManager')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'business_managers_users',
            },
        ),
    ]
