# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('business_manager', '0002_businessmanageruserjointable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessmanageruserjointable',
            unique_together=set([('business_manager', 'user')]),
        ),
    ]
