# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('business_manager', '0002_businessmanageruserjointable'),
        ('ad_account', '0002_adaccountbusinessmanagerjointable_adaccountuserjointable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adaccountbusinessmanagerjointable',
            unique_together=set([('ad_account', 'business_manager')]),
        ),
        migrations.AlterUniqueTogether(
            name='adaccountuserjointable',
            unique_together=set([('ad_account', 'user')]),
        ),
    ]
