# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_account', '0003_auto_20170327_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30),
        ),
    ]
